[project]
name = "banko-backend"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.24",
]

[tool.uv]
dev-dependencies = ["ruff>=0.11.2"]
