// This file is auto-generated by @hey-api/openapi-ts

export type FinanceResponse = {
    income: number;
    expense: number;
};

export type GetByCategoriesFinanceResponse = {
    income: number;
    expense: number;
    percentageOfTotalIncome: number;
    percentageOfTotalExpense: number;
};

export type GetByCategoriesRequest = {
    startDate: string;
    endDate: string;
};

export type GetByCategoriesResponse = {
    financeByCategory: {
        [key: string]: GetByCategoriesFinanceResponse;
    };
};

export type GetFinancialChartRequest = {
    startDate: string;
    endDate: string;
    groupBy: 'day' | 'week' | 'month' | 'year' | 'total';
};

export type GetFinancialChartResponse = {
    financeByPeriod: {
        [key: string]: FinanceResponse;
    };
};

export type GetFinancialSummaryRequest = {
    startDate: string;
    endDate: string;
};

export type GetFinancialSummaryResponse = {
    income: number;
    expense: number;
    balance: number;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetFinancialChartFinancialChartPostData = {
    body: GetFinancialChartRequest;
    path?: never;
    query?: never;
    url: '/financial_chart';
};

export type GetFinancialChartFinancialChartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFinancialChartFinancialChartPostError = GetFinancialChartFinancialChartPostErrors[keyof GetFinancialChartFinancialChartPostErrors];

export type GetFinancialChartFinancialChartPostResponses = {
    /**
     * Successful Response
     */
    200: GetFinancialChartResponse;
};

export type GetFinancialChartFinancialChartPostResponse = GetFinancialChartFinancialChartPostResponses[keyof GetFinancialChartFinancialChartPostResponses];

export type GetSummarySummaryPostData = {
    body: GetFinancialSummaryRequest;
    path?: never;
    query?: never;
    url: '/summary';
};

export type GetSummarySummaryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSummarySummaryPostError = GetSummarySummaryPostErrors[keyof GetSummarySummaryPostErrors];

export type GetSummarySummaryPostResponses = {
    /**
     * Successful Response
     */
    200: GetFinancialSummaryResponse;
};

export type GetSummarySummaryPostResponse = GetSummarySummaryPostResponses[keyof GetSummarySummaryPostResponses];

export type GetByCategoriesByCategoriesPostData = {
    body: GetByCategoriesRequest;
    path?: never;
    query?: never;
    url: '/by_categories';
};

export type GetByCategoriesByCategoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByCategoriesByCategoriesPostError = GetByCategoriesByCategoriesPostErrors[keyof GetByCategoriesByCategoriesPostErrors];

export type GetByCategoriesByCategoriesPostResponses = {
    /**
     * Successful Response
     */
    200: GetByCategoriesResponse;
};

export type GetByCategoriesByCategoriesPostResponse = GetByCategoriesByCategoriesPostResponses[keyof GetByCategoriesByCategoriesPostResponses];

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};