// This file is auto-generated by @hey-api/openapi-ts

export type BodyGetImportInfoImportInfoPost = {
    file: Blob | File;
};

export type BodyImportTransactionsImportTransactionsPost = {
    file: Blob | File;
    form_mapping: string;
};

export type FinanceResponse = {
    income: number;
    expense: number;
};

export type GetByCategoriesFinanceResponse = {
    income: number;
    expense: number;
    percentageOfTotalIncome: number;
    percentageOfTotalExpense: number;
};

export type GetByCategoriesRequest = {
    startDate: string;
    endDate: string;
};

export type GetByCategoriesResponse = {
    financeByCategory: {
        [key: string]: GetByCategoriesFinanceResponse;
    };
};

export type GetCurrencyResponse = {
    currencyLabel: string;
    currencySymbol: string;
    currencyCode: string;
};

export type GetFinancialChartRequest = {
    startDate: string;
    endDate: string;
    groupBy: 'day' | 'week' | 'month' | 'year' | 'total';
};

export type GetFinancialChartResponse = {
    financeByPeriod: {
        [key: string]: FinanceResponse;
    };
};

export type GetFinancialSummaryRequest = {
    startDate: string;
    endDate: string;
};

export type GetFinancialSummaryResponse = {
    income: number;
    expense: number;
    balance: number;
};

export type GetTransactionResponse = {
    at: string;
    name: string;
    category: string;
    amount: number;
};

export type GetTransactionsRequest = {
    startDate: string;
    endDate: string;
    transactionType: 'income' | 'expense' | 'all';
};

export type GetTransactionsResponse = {
    transactions: Array<GetTransactionResponse>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ImportHistoryResponse = {
    at: string;
    fileName: string;
    imported: number;
};

export type ImportInfoResponse = {
    headers: Array<string>;
    firstValuesByHeader: {
        [key: string]: Array<string>;
    };
};

export type ImportTransactionsResponse = {
    imported: number;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type GetFinancialChartFinancialChartPostData = {
    body: GetFinancialChartRequest;
    path?: never;
    query?: never;
    url: '/financial_chart';
};

export type GetFinancialChartFinancialChartPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetFinancialChartFinancialChartPostError = GetFinancialChartFinancialChartPostErrors[keyof GetFinancialChartFinancialChartPostErrors];

export type GetFinancialChartFinancialChartPostResponses = {
    /**
     * Successful Response
     */
    200: GetFinancialChartResponse;
};

export type GetFinancialChartFinancialChartPostResponse = GetFinancialChartFinancialChartPostResponses[keyof GetFinancialChartFinancialChartPostResponses];

export type GetSummarySummaryPostData = {
    body: GetFinancialSummaryRequest;
    path?: never;
    query?: never;
    url: '/summary';
};

export type GetSummarySummaryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSummarySummaryPostError = GetSummarySummaryPostErrors[keyof GetSummarySummaryPostErrors];

export type GetSummarySummaryPostResponses = {
    /**
     * Successful Response
     */
    200: GetFinancialSummaryResponse;
};

export type GetSummarySummaryPostResponse = GetSummarySummaryPostResponses[keyof GetSummarySummaryPostResponses];

export type GetByCategoriesByCategoriesPostData = {
    body: GetByCategoriesRequest;
    path?: never;
    query?: never;
    url: '/by_categories';
};

export type GetByCategoriesByCategoriesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByCategoriesByCategoriesPostError = GetByCategoriesByCategoriesPostErrors[keyof GetByCategoriesByCategoriesPostErrors];

export type GetByCategoriesByCategoriesPostResponses = {
    /**
     * Successful Response
     */
    200: GetByCategoriesResponse;
};

export type GetByCategoriesByCategoriesPostResponse = GetByCategoriesByCategoriesPostResponses[keyof GetByCategoriesByCategoriesPostResponses];

export type TransactionsTransactionsPostData = {
    body: GetTransactionsRequest;
    path?: never;
    query?: never;
    url: '/transactions';
};

export type TransactionsTransactionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TransactionsTransactionsPostError = TransactionsTransactionsPostErrors[keyof TransactionsTransactionsPostErrors];

export type TransactionsTransactionsPostResponses = {
    /**
     * Successful Response
     */
    200: GetTransactionsResponse;
};

export type TransactionsTransactionsPostResponse = TransactionsTransactionsPostResponses[keyof TransactionsTransactionsPostResponses];

export type GetCurrencyCurrencyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/currency';
};

export type GetCurrencyCurrencyGetResponses = {
    /**
     * Successful Response
     */
    200: GetCurrencyResponse;
};

export type GetCurrencyCurrencyGetResponse = GetCurrencyCurrencyGetResponses[keyof GetCurrencyCurrencyGetResponses];

export type GetImportInfoImportInfoPostData = {
    body: BodyGetImportInfoImportInfoPost;
    path?: never;
    query?: never;
    url: '/import/info';
};

export type GetImportInfoImportInfoPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetImportInfoImportInfoPostError = GetImportInfoImportInfoPostErrors[keyof GetImportInfoImportInfoPostErrors];

export type GetImportInfoImportInfoPostResponses = {
    /**
     * Successful Response
     */
    200: ImportInfoResponse;
};

export type GetImportInfoImportInfoPostResponse = GetImportInfoImportInfoPostResponses[keyof GetImportInfoImportInfoPostResponses];

export type ImportTransactionsImportTransactionsPostData = {
    body: BodyImportTransactionsImportTransactionsPost;
    path?: never;
    query: {
        file_name: string;
    };
    url: '/import/transactions';
};

export type ImportTransactionsImportTransactionsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportTransactionsImportTransactionsPostError = ImportTransactionsImportTransactionsPostErrors[keyof ImportTransactionsImportTransactionsPostErrors];

export type ImportTransactionsImportTransactionsPostResponses = {
    /**
     * Successful Response
     */
    200: ImportTransactionsResponse;
};

export type ImportTransactionsImportTransactionsPostResponse = ImportTransactionsImportTransactionsPostResponses[keyof ImportTransactionsImportTransactionsPostResponses];

export type ImportHistoryImportHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/import/history';
};

export type ImportHistoryImportHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: Array<ImportHistoryResponse>;
};

export type ImportHistoryImportHistoryGetResponse = ImportHistoryImportHistoryGetResponses[keyof ImportHistoryImportHistoryGetResponses];

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8000' | (string & {});
};